name: wradlib-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pip
  - ablog
  - colorspacious
  - ipywidgets
  - jupyterlab>=3
  - myst-nb>=0.12.0
  - pip
  - pydata-sphinx-theme>=0.4.3
  - python-graphviz
  - seaborn
  - sphinx
  - sphinx-autobuild
  - sphinx-comments
  - sphinx-panels
  - sphinxcontrib-bibtex<2.0.0
  - sphinxext-rediraffe
  - sphinx-design
  - sphinx-copybutton
  - pip:
      - sphinxext-opengraph